### ISSUE TITLE
English Wikitravel fails to download images

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fsrrt/wikiteam#37]
```
Checking api.php...
api.php is OK
Checking index.php...
index.php is OK
Analysing http://wikitravel.org/wiki/en/api.php
Loading config file...
Resuming previous dump process...
Title list was completed in the previous session
XML dump was completed in the previous session
Image list is incomplete. Reloading...
Retrieving image filenames
Traceback (most recent call last):
  File "dumpgenerator.py", line 1013, in <module>
    main()
  File "dumpgenerator.py", line 936, in main
    images = getImageFilenamesURL(config=config)
  File "dumpgenerator.py", line 447, in getImageFilenamesURL
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

```

Original issue reported on code.google.com by `emi...@gmail.com` on 26 Jul 2011 at 8:36
- Blocking: #44, #44

**Comment by GoogleCodeExporter** [comment]
```
#22 again? This is probably Special:ListFiles killing the server.
```

Original comment by `nemow...@gmail.com` on 29 Feb 2012 at 11:29

**Comment by GoogleCodeExporter** [comment]
Original comment by `nemow...@gmail.com` on 29 Feb 2012 at 11:41

**Comment by GoogleCodeExporter** [comment]
Original comment by `ad...@alphacorp.tk` on 22 Jun 2012 at 10:02
- Now blocking: #44, #44
