### ISSUE TITLE
The API check should check that the API actually works

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fsrrt/wikiteam#48]
```
http://dachaja.net/api.php taken from the new list:

Checking api.php...
api.php is OK
Traceback (most recent call last):
  File "dumpgenerator.py", line 1029, in <module>
    main()
  File "dumpgenerator.py", line 838, in main
    config, other = getParameters(params=params)
  File "dumpgenerator.py", line 795, in getParameters
    if checkIndexphp(config['index']):
  File "dumpgenerator.py", line 818, in checkIndexphp
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error


The wiki has some database problems, so some queries work and some don't. For 
instance http://dachaja.net/api.php?action=query&meta=siteinfo :

<error code="internal_api_error_DBQueryError" info="Database query error" 
xml:space="preserve" />

and by the way the main page gives a DB error

from within function "SqlBagOStuff::get". Database returned error "144: Table 
'./Dachaja_net/Dachaja_netobjectcache' is marked as crashed and last 
(automatic?) repair failed (localhost)".
```

Original issue reported on code.google.com by `nemow...@gmail.com` on 8 Apr 2012 at 7:38
- Blocked on: #97

**Comment by GoogleCodeExporter** [comment]
```
Fixing this is easy, we only need to check what's the earliest and most 
continuously available API call and to use it.
```

Original comment by `nemow...@gmail.com` on 31 Jan 2014 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
In issue 97 I suggest we use siteinfo.
```

Original comment by `nemow...@gmail.com` on 2 Feb 2014 at 7:43
- Now blocked on: #97

**Comment by GoogleCodeExporter** [comment]
```
That wiki was fixed, asking Google for more ideas: 
https://encrypted.google.com/search?q="internal_api_error"+inurl%3Aapi.php

http://sudoco.espaces-naturels.fr/wiki/index.php fatals on index
http://www.sci-mate.org/wiki/api.php is a good candidate: api.php works, but 
<http://www.sci-mate.org/wiki/api.php?action=query&meta=siteinfo> gives   
<error code="internal_api_error" info="Exception Caught: DB connection error: 
Unknown MySQL server host 'DB_HOST' (2) (DB_HOST)">
```

Original comment by `nemow...@gmail.com` on 27 Feb 2014 at 1:35
