### ISSUE TITLE
HTTP Error 403: Bad Behavior on dumping start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fsrrt/wikiteam#62]
```
dumpgenerator.py r829
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on 
win32
MediaWiki 1.19.2 (http://liswiki.org/wiki/Special:Version)

dumpgenerator.py --api=http://liswiki.org/w/api.php --xml --images

Checking api.php... http://liswiki.org/w/api.php
api.php is OK
Traceback (most recent call last):
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 1157, in <module
>
    main()
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 1114, in main
    config, other = getParameters(params=params)
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 879, in getParam
eters
    if checkIndexphp(config['index']):
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 904, in checkInd
exphp
    f = urllib2.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Bad Behavior

------------------------------------------------------------

dumpgenerator.py --index=http://liswiki.org/w/index.php --xml --images

Traceback (most recent call last):
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 1157, in <module
>
    main()
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 1114, in main
    config, other = getParameters(params=params)
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 879, in getParam
eters
    if checkIndexphp(config['index']):
  File "C:\Users\Luiz Augusto\Downloads\dumpgenerator.py", line 904, in checkInd
exphp
    f = urllib2.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Bad Behavior
```

Original issue reported on code.google.com by `lugu...@gmail.com` on 17 Aug 2013 at 5:09

**Comment by GoogleCodeExporter** [comment]
```
Hi Lugusto, can you please retest this with the last code? I made some changes 
that could/should have fixed it.
```

Original comment by `nemow...@gmail.com` on 25 Oct 2013 at 12:44

**Comment by GoogleCodeExporter** [comment]
```
Still didn't worked

I'm running on Win7 Home Premium SP1 x64 with Python 2.7.5 (unable to try on 
Linux based systems ATM)
```

Original comment by `lugu...@gmail.com` on 26 Oct 2013 at 12:48

Attachments:
- [-index.log](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-62/comment-2/-index.log)
- [-api.log](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-62/comment-2/-api.log)

**Comment by GoogleCodeExporter** [comment]
```
Ran into this as well. Its caused by something in the user agent. 
http://stackoverflow.com/questions/3336549/pythons-urllib2-why-do-i-get-error-40
3-when-i-urlopen-a-wikipedia-page 
This fix worked for me
```

Original comment by `rob....@gmail.com` on 3 Nov 2013 at 8:55

**Comment by GoogleCodeExporter** [comment]
```
Many thanks!

Partially worked with r861 and changing the relevant line to

    useragents = ['Magic Browser']
, see the log
```

Original comment by `lugu...@gmail.com` on 8 Nov 2013 at 2:20

Attachments:
- [api_livehack_20131107.log](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-62/comment-4/api_livehack_20131107.log)

**Comment by GoogleCodeExporter** [comment]
```
Lugusto, please try again now (r864). Also, they are kind enough to say, in 
their http://liswiki.org/robots.txt , Crawl-delay: 45. So let's be nice, given 
that their server seems quite slow, and use --delay=45 (start it a few minutes 
after your last visit to the website). I've made the delay work in several 
places where it was ignored.
```

Original comment by `nemow...@gmail.com` on 8 Nov 2013 at 10:24

**Comment by GoogleCodeExporter** [comment]
```
Many many thanks =D

Working with r866 + delay + useragent livehack (didn't worked without this even 
with r866 + delay)
```

Original comment by `lugu...@gmail.com` on 10 Nov 2013 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
Good. Too bad for the user agent, I hope we chose it correctly; but it's 
expected that you may have to customise it.
```

Original comment by `nemow...@gmail.com` on 10 Nov 2013 at 9:18
- Changed state: **Fixed**
