### ISSUE TITLE
dumpgenerator.py crashes on some images without higher resolution

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fsrrt/wikiteam#63]
```
Running r829. Successfully fully dumped 35 Wikia wikis until now, but got 
crashed in 3 more Wikia wikis and 1 non-Wikia MediaWiki wiki.

All related media files don't have higher resolutions, maybe this is the 
reason. List of media files:

http://pt.saintseiya.wikia.com/wiki/Ficheiro:Atena.png
http://pt-br.ben10.wikia.com/wiki/Arquivo:185px-Alien_Planta.jpg
http://wikimerda.org/wiki/Arquivo:331px-Longcat.jpg

See attachments for commands and log files

(phineaseferb_ptbr.sh didn't generate log files until now. I will update this 
report when/if it generates)
```

Original issue reported on code.google.com by `lugu...@gmail.com` on 23 Aug 2013 at 4:15
- Merged into: #86

Attachments:
- [ben10_ptbr.log](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-63/comment-0/ben10_ptbr.log)
- [ben10_ptbr.sh](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-63/comment-0/ben10_ptbr.sh)
- [phineaseferb_ptbr.sh](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-63/comment-0/phineaseferb_ptbr.sh)
- [saintseiya_pt.log](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-63/comment-0/saintseiya_pt.log)
- [saintseiya_pt.sh](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-63/comment-0/saintseiya_pt.sh)
- [wikimerda_org.log](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-63/comment-0/wikimerda_org.log)
- [wikimerda_org.sh](https://storage.googleapis.com/google-code-attachments/wikiteam/issue-63/comment-0/wikimerda_org.sh)

**Comment by GoogleCodeExporter** [comment]
```
phineaseferb_ptbr.sh finished successfully with no single change from my side 
(maybe at Wikia side? o.O )

Will try to run the anothers ones liste here again in some hours (currently my 
VPS is overloaded).
```

Original comment by `lugu...@gmail.com` on 23 Aug 2013 at 11:01

**Comment by GoogleCodeExporter** [comment]
```
> Will try to run the anothers ones liste here again in some hours

Lugusto, did it work in the end?
```

Original comment by `nemow...@gmail.com` on 9 Sep 2013 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
So sorry for the long delay. I'm running again those projects on a different 
VPS and all is working fine until now (wikimerda_org.sh finished with no 
errors), using r831
```

Original comment by `lugu...@gmail.com` on 21 Sep 2013 at 10:56

**Comment by GoogleCodeExporter** [comment]
```
Not fixed...

Checking api.php... http://pt.saintseiya.wikia.com/api.php
api.php is OK
Checking index.php... http://pt.saintseiya.wikia.com/index.php
index.php is OK
Analysing http://pt.saintseiya.wikia.com/api.php
Loading config file...
Resuming previous dump process...
Title list was completed in the previous session
XML dump was completed in the previous session
Image list was completed in the previous session
3485 images were found in the directory from a previous session
Retrieving images from "Atena.png"
Traceback (most recent call last):
  File "./dumpgenerator.py", line 1161, in <module>
    main()
  File "./dumpgenerator.py", line 1152, in main
    resumePreviousDump(config=config, other=other)
  File "./dumpgenerator.py", line 1068, in resumePreviousDump
    generateImageDump(config=config, other=other, images=images, start=lastfilename2) # we resume from previous image, which may be corrupted (or missing .desc)  by the previous session ctrl-c or abort
  File "./dumpgenerator.py", line 652, in generateImageDump
    urllib.urlretrieve(url=url, filename='%s/%s' % (imagepath, filename2), data=urllib.urlencode({})) #fix, image request fails on wikipedia (POST neither works?)
  File "/usr/lib/python2.7/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 243, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: 
'./ptsaintseiyawikiacom-20130921-wikidump/images/Atena/.jpg'
```

Original comment by `lugu...@gmail.com` on 23 Sep 2013 at 1:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `nemow...@gmail.com` on 25 Oct 2013 at 12:43
- Changed title: **dumpgenerator.py crashes on some images without higher resolution**

**Comment by GoogleCodeExporter** [comment]
```
I tried this again... wikimerda worked for me too, but the others give 
"urllib2.HTTPError: HTTP Error 404: Not Found": can you please find an URL at 
which the index.php/api.php can be accessed?
```

Original comment by `nemow...@gmail.com` on 10 Nov 2013 at 9:19

**Comment by GoogleCodeExporter** [comment]
```
I will retry those from scratch in a few hours, with a possible delay of some 
additional hours to get the error again
```

Original comment by `lugu...@gmail.com` on 11 Nov 2013 at 3:29

**Comment by GoogleCodeExporter** [comment]
```
Of the attachments above, wikimerda_org.log was a network problem of the wiki; 
saintseiya_pt.log and ben10_ptbr.log both show errors on filenames with a 
slash: merging to issue 86.
```

Original comment by `nemow...@gmail.com` on 31 Jan 2014 at 3:25
- Changed state: **Duplicate**
